// Generated by `npm run schema:migrations`. Do not edit: change src/Store/Schema.ts instead.

/** One step from whatever a database is to what the schema says, and what it is called. */
export type Migration = {
  name: string;
  statements: readonly string[];
};

export const migrations: readonly Migration[] = [
  {
    "name": "20260814094740_greedy_nebula",
    "statements": [
      "CREATE TABLE `carried_run` (\n\t`run_id` text PRIMARY KEY,\n\t`server_run` text NOT NULL,\n\t`carried_at` text NOT NULL,\n\tCONSTRAINT `fk_carried_run_run_id_run_id_fk` FOREIGN KEY (`run_id`) REFERENCES `run`(`id`) ON DELETE CASCADE\n);",
      "CREATE TABLE `desired_state` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT,\n\t`target` text NOT NULL,\n\t`revision` integer NOT NULL,\n\t`declaration` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tCONSTRAINT `fk_desired_state_target_target_name_fk` FOREIGN KEY (`target`) REFERENCES `target`(`name`) ON DELETE CASCADE,\n\tCONSTRAINT `desired_state_target_revision_unique` UNIQUE(`target`,`revision`)\n);",
      "CREATE TABLE `fact_snapshot` (\n\t`id` text PRIMARY KEY,\n\t`target` text NOT NULL,\n\t`run_id` text,\n\t`schema_version` text NOT NULL,\n\t`captured_at` text NOT NULL,\n\t`data` text NOT NULL,\n\tCONSTRAINT `fk_fact_snapshot_target_target_name_fk` FOREIGN KEY (`target`) REFERENCES `target`(`name`) ON DELETE CASCADE\n);",
      "CREATE TABLE `machine_image` (\n\t`target` text PRIMARY KEY,\n\t`reference` text NOT NULL,\n\t`url` text NOT NULL,\n\t`sha256` text NOT NULL,\n\t`platform` text NOT NULL,\n\t`architecture` text NOT NULL,\n\t`format` text NOT NULL,\n\t`boot` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tCONSTRAINT `fk_machine_image_target_target_name_fk` FOREIGN KEY (`target`) REFERENCES `target`(`name`) ON DELETE CASCADE\n);",
      "CREATE TABLE `requirement_run` (\n\t`id` text PRIMARY KEY,\n\t`target` text NOT NULL,\n\t`run_id` text,\n\t`status` text NOT NULL,\n\t`evaluated_at` text NOT NULL,\n\t`results` text NOT NULL,\n\tCONSTRAINT `fk_requirement_run_target_target_name_fk` FOREIGN KEY (`target`) REFERENCES `target`(`name`) ON DELETE CASCADE,\n\tCONSTRAINT `fk_requirement_run_run_id_run_id_fk` FOREIGN KEY (`run_id`) REFERENCES `run`(`id`) ON DELETE CASCADE\n);",
      "CREATE TABLE `run` (\n\t`id` text PRIMARY KEY,\n\t`target` text NOT NULL,\n\t`command` text NOT NULL,\n\t`status` text NOT NULL,\n\t`started_at` text NOT NULL,\n\t`finished_at` text,\n\tCONSTRAINT `fk_run_target_target_name_fk` FOREIGN KEY (`target`) REFERENCES `target`(`name`) ON DELETE CASCADE\n);",
      "CREATE TABLE `run_image` (\n\t`run_id` text PRIMARY KEY,\n\t`reference` text NOT NULL,\n\t`url` text NOT NULL,\n\t`sha256` text NOT NULL,\n\tCONSTRAINT `fk_run_image_run_id_run_id_fk` FOREIGN KEY (`run_id`) REFERENCES `run`(`id`) ON DELETE CASCADE\n);",
      "CREATE TABLE `run_step` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT,\n\t`run_id` text NOT NULL,\n\t`ordinal` integer NOT NULL,\n\t`name` text NOT NULL,\n\t`status` text NOT NULL,\n\t`started_at` text NOT NULL,\n\t`finished_at` text,\n\t`detail` text,\n\tCONSTRAINT `fk_run_step_run_id_run_id_fk` FOREIGN KEY (`run_id`) REFERENCES `run`(`id`) ON DELETE CASCADE,\n\tCONSTRAINT `run_step_run_id_ordinal_unique` UNIQUE(`run_id`,`ordinal`)\n);",
      "CREATE TABLE `target` (\n\t`name` text PRIMARY KEY,\n\t`scope` text NOT NULL,\n\t`type` text NOT NULL,\n\t`provider` text,\n\t`transport` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);"
    ]
  },
  {
    "name": "20260814105708_drop_what_nothing_reads",
    "statements": [
      "-- Three tables openstrap stopped writing and never read again.\n--\n-- `allocated_port` recorded which host port was forwarded, and the provider forwarding it answers\n-- that on request. `provider_resource` recorded a machine's id, and `provider.find(name)` answers\n-- that. `secret_reference` recorded where a key was kept, and keys became the transport's.\n--\n-- Written by hand because there is nothing to generate them from: a schema describes what is, and\n-- these have not been in it since they were removed. Drizzle can only diff against what it knows.\nDROP TABLE IF EXISTS allocated_port;",
      "DROP TABLE IF EXISTS provider_resource;",
      "DROP TABLE IF EXISTS secret_reference;"
    ]
  },
  {
    "name": "20260814105747_drop_machine_platform",
    "statements": [
      "-- A table from before the one that replaced it.\n--\n-- `machine_platform` said what kind of machine a target was; `machine_image` says that and what it\n-- was made from, in one row, because two rows about one thing drift (ADR 0003). The replacement\n-- landed and the old table stayed behind, unread, in every database made before it.\nDROP TABLE IF EXISTS machine_platform;"
    ]
  },
  {
    "name": "20260814164024_groovy_machine_man",
    "statements": [
      "PRAGMA foreign_keys=OFF;",
      "CREATE TABLE `__new_machine_image` (\n\t`target` text PRIMARY KEY,\n\t`reference` text NOT NULL,\n\t`url` text NOT NULL,\n\t`sha256` text,\n\t`platform` text NOT NULL,\n\t`architecture` text NOT NULL,\n\t`format` text NOT NULL,\n\t`boot` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tCONSTRAINT `fk_machine_image_target_target_name_fk` FOREIGN KEY (`target`) REFERENCES `target`(`name`) ON DELETE CASCADE\n);",
      "INSERT INTO `__new_machine_image`(`target`, `reference`, `url`, `sha256`, `platform`, `architecture`, `format`, `boot`, `created_at`) SELECT `target`, `reference`, `url`, `sha256`, `platform`, `architecture`, `format`, `boot`, `created_at` FROM `machine_image`;",
      "DROP TABLE `machine_image`;",
      "ALTER TABLE `__new_machine_image` RENAME TO `machine_image`;",
      "PRAGMA foreign_keys=ON;",
      "PRAGMA foreign_keys=OFF;",
      "CREATE TABLE `__new_run_image` (\n\t`run_id` text PRIMARY KEY,\n\t`reference` text NOT NULL,\n\t`url` text NOT NULL,\n\t`sha256` text,\n\tCONSTRAINT `fk_run_image_run_id_run_id_fk` FOREIGN KEY (`run_id`) REFERENCES `run`(`id`) ON DELETE CASCADE\n);",
      "INSERT INTO `__new_run_image`(`run_id`, `reference`, `url`, `sha256`) SELECT `run_id`, `reference`, `url`, `sha256` FROM `run_image`;",
      "DROP TABLE `run_image`;",
      "ALTER TABLE `__new_run_image` RENAME TO `run_image`;",
      "PRAGMA foreign_keys=ON;"
    ]
  }
];
